---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: rag-arxiv-elt-
spec:
  entrypoint: elt

  volumes:
    - name: bronze
      persistentVolumeClaim:
        claimName: rag-arxiv-bronze

    - name: silver
      persistentVolumeClaim:
        claimName: rag-arxiv-silver

    - name: gold
      persistentVolumeClaim:
        claimName: rag-arxiv-gold

  templates:
    - name: extract
      container:
        image: rag-arxiv_extract
        imagePullPolicy: Never
        command:
         - sh
         - extract.sh

        volumeMounts:
          - name: bronze
            mountPath: /data/bronze

        env:
          - name: ARXIV_RAW_DIR
            value: /data/bronze

          - name: KAGGLE_USERNAME
            valueFrom:
              secretKeyRef:
                name: kaggle
                key: username

          - name: KAGGLE_KEY
            valueFrom:
              secretKeyRef:
                name: kaggle
                key: key

    - name: load
      container:
        image: rag-arxiv_load
        imagePullPolicy: Never
        command:
         - sh
         - load.sh

        volumeMounts:
          - name: bronze
            mountPath: /data/bronze

          - name: silver
            mountPath: /data/silver

        env:
          - name: ARXIV_RAW_DIR
            value: /data/bronze

          - name: ARXIV_CLEAN_FP
            value: /data/silver/arxiv.parquet

    - name: transform
      container:
        image: rag-arxiv_transform
        imagePullPolicy: Never
        command:
         - sh
         - transform.sh

        volumeMounts:
          - name: bronze
            mountPath: /data/bronze

          - name: silver
            mountPath: /data/silver

          - name: gold
            mountPath: /data/gold

        env:
          - name: ARXIV_CLEAN_FP
            value: /data/silver/arxiv.parquet

          - name: ARXIV_DOC_FP
            value: /data/gold/arxiv-rag-doc.parquet


    - name: elt
      dag:
        tasks:
          - name: extract
            template: extract

          - name: load
            dependencies: [extract]
            template: load

          - name: transform
            dependencies: [load]
            template: transform

